// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64
// +build 386 amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type GoftraceArgData struct {
	Goid uint64
	Data [64]uint8
}

type GoftraceArgRule struct {
	Type        uint8
	Reg         uint8
	Size        uint8
	Length      uint8
	Offsets     [8]int16
	Dereference [8]uint8
}

type GoftraceArgRules struct {
	Length uint8
	_      [1]byte
	Rules  [8]GoftraceArgRule
}

type GoftraceEvent struct {
	Goid     uint64
	Ip       uint64
	Bp       uint64
	CallerIp uint64
	CallerBp uint64
	TimeNs   uint64
	Location uint8
	_        [7]byte
}

// LoadGoftrace returns the embedded CollectionSpec for Goftrace.
func LoadGoftrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GoftraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Goftrace: %w", err)
	}

	return spec, err
}

// LoadGoftraceObjects loads Goftrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GoftraceObjects
//	*GoftracePrograms
//	*GoftraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGoftraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGoftrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GoftraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GoftraceSpecs struct {
	GoftraceProgramSpecs
	GoftraceMapSpecs
}

// GoftraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GoftraceProgramSpecs struct {
	Ent           *ebpf.ProgramSpec `ebpf:"ent"`
	GoroutineExit *ebpf.ProgramSpec `ebpf:"goroutine_exit"`
	Ret           *ebpf.ProgramSpec `ebpf:"ret"`
}

// GoftraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GoftraceMapSpecs struct {
	ArgQueue        *ebpf.MapSpec `ebpf:"arg_queue"`
	ArgRulesMap     *ebpf.MapSpec `ebpf:"arg_rules_map"`
	ArgStack        *ebpf.MapSpec `ebpf:"arg_stack"`
	EventQueue      *ebpf.MapSpec `ebpf:"event_queue"`
	EventStack      *ebpf.MapSpec `ebpf:"event_stack"`
	ShouldTraceGoid *ebpf.MapSpec `ebpf:"should_trace_goid"`
	ShouldTraceRip  *ebpf.MapSpec `ebpf:"should_trace_rip"`
}

// GoftraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGoftraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type GoftraceObjects struct {
	GoftracePrograms
	GoftraceMaps
}

func (o *GoftraceObjects) Close() error {
	return _GoftraceClose(
		&o.GoftracePrograms,
		&o.GoftraceMaps,
	)
}

// GoftraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGoftraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type GoftraceMaps struct {
	ArgQueue        *ebpf.Map `ebpf:"arg_queue"`
	ArgRulesMap     *ebpf.Map `ebpf:"arg_rules_map"`
	ArgStack        *ebpf.Map `ebpf:"arg_stack"`
	EventQueue      *ebpf.Map `ebpf:"event_queue"`
	EventStack      *ebpf.Map `ebpf:"event_stack"`
	ShouldTraceGoid *ebpf.Map `ebpf:"should_trace_goid"`
	ShouldTraceRip  *ebpf.Map `ebpf:"should_trace_rip"`
}

func (m *GoftraceMaps) Close() error {
	return _GoftraceClose(
		m.ArgQueue,
		m.ArgRulesMap,
		m.ArgStack,
		m.EventQueue,
		m.EventStack,
		m.ShouldTraceGoid,
		m.ShouldTraceRip,
	)
}

// GoftracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGoftraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type GoftracePrograms struct {
	Ent           *ebpf.Program `ebpf:"ent"`
	GoroutineExit *ebpf.Program `ebpf:"goroutine_exit"`
	Ret           *ebpf.Program `ebpf:"ret"`
}

func (p *GoftracePrograms) Close() error {
	return _GoftraceClose(
		p.Ent,
		p.GoroutineExit,
		p.Ret,
	)
}

func _GoftraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed goftrace_bpfel_x86.o
var _GoftraceBytes []byte
