// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64
// +build 386 amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type GoftraceArgData struct {
	Data      [64]uint8
	IsNil     uint8
	ReadError uint8
	Padding   [6]uint8
}

type GoftraceArgRule struct {
	Type        uint8
	Reg         uint8
	Size        uint8
	Length      uint8
	Offsets     [8]int16
	Dereference [8]uint8
	NilCheck    uint8
	_           [1]byte
}

type GoftraceArgRules struct {
	Length uint8
	_      [1]byte
	Rules  [8]GoftraceArgRule
}

type GoftraceEvent struct {
	Goid              uint64
	Ip                uint64
	Bp                uint64
	CallerIp          uint64
	CallerBp          uint64
	TimeNs            uint64
	Pid               uint32
	SampleDenominator uint32
	Location          uint8
	ArgCount          uint8
	TraceFlags        uint8
	Padding           uint8
	Args              [8]GoftraceArgData
	_                 [4]byte
}

type GoftraceRuntimeStats struct {
	WantedRoots         uint64
	AdmittedRoots       uint64
	SampledOutRoots     uint64
	EmittedEvents       uint64
	DroppedEvents       uint64
	AbortedRoots        uint64
	StateInsertFailures uint64
}

type GoftraceSampleConfig struct {
	Denominator uint32
	Pad         uint32
}

type GoftraceTraceState struct {
	RootIp            uint64
	LastIp            uint64
	LastBp            uint64
	RootDepth         uint32
	EventCount        uint32
	SampleDenominator uint32
	Pad               uint32
}

// LoadGoftrace returns the embedded CollectionSpec for Goftrace.
func LoadGoftrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GoftraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Goftrace: %w", err)
	}

	return spec, err
}

// LoadGoftraceObjects loads Goftrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GoftraceObjects
//	*GoftracePrograms
//	*GoftraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGoftraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGoftrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GoftraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GoftraceSpecs struct {
	GoftraceProgramSpecs
	GoftraceMapSpecs
}

// GoftraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GoftraceProgramSpecs struct {
	Ent           *ebpf.ProgramSpec `ebpf:"ent"`
	GoroutineExit *ebpf.ProgramSpec `ebpf:"goroutine_exit"`
	Ret           *ebpf.ProgramSpec `ebpf:"ret"`
}

// GoftraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GoftraceMapSpecs struct {
	ArgRulesMap     *ebpf.MapSpec `ebpf:"arg_rules_map"`
	EventBuffer     *ebpf.MapSpec `ebpf:"event_buffer"`
	EventQueue      *ebpf.MapSpec `ebpf:"event_queue"`
	RuntimeStatsMap *ebpf.MapSpec `ebpf:"runtime_stats_map"`
	SampleConfigMap *ebpf.MapSpec `ebpf:"sample_config_map"`
	ShouldTraceGoid *ebpf.MapSpec `ebpf:"should_trace_goid"`
	ShouldTraceRet  *ebpf.MapSpec `ebpf:"should_trace_ret"`
	ShouldTraceRip  *ebpf.MapSpec `ebpf:"should_trace_rip"`
}

// GoftraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGoftraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type GoftraceObjects struct {
	GoftracePrograms
	GoftraceMaps
}

func (o *GoftraceObjects) Close() error {
	return _GoftraceClose(
		&o.GoftracePrograms,
		&o.GoftraceMaps,
	)
}

// GoftraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGoftraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type GoftraceMaps struct {
	ArgRulesMap     *ebpf.Map `ebpf:"arg_rules_map"`
	EventBuffer     *ebpf.Map `ebpf:"event_buffer"`
	EventQueue      *ebpf.Map `ebpf:"event_queue"`
	RuntimeStatsMap *ebpf.Map `ebpf:"runtime_stats_map"`
	SampleConfigMap *ebpf.Map `ebpf:"sample_config_map"`
	ShouldTraceGoid *ebpf.Map `ebpf:"should_trace_goid"`
	ShouldTraceRet  *ebpf.Map `ebpf:"should_trace_ret"`
	ShouldTraceRip  *ebpf.Map `ebpf:"should_trace_rip"`
}

func (m *GoftraceMaps) Close() error {
	return _GoftraceClose(
		m.ArgRulesMap,
		m.EventBuffer,
		m.EventQueue,
		m.RuntimeStatsMap,
		m.SampleConfigMap,
		m.ShouldTraceGoid,
		m.ShouldTraceRet,
		m.ShouldTraceRip,
	)
}

// GoftracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGoftraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type GoftracePrograms struct {
	Ent           *ebpf.Program `ebpf:"ent"`
	GoroutineExit *ebpf.Program `ebpf:"goroutine_exit"`
	Ret           *ebpf.Program `ebpf:"ret"`
}

func (p *GoftracePrograms) Close() error {
	return _GoftraceClose(
		p.Ent,
		p.GoroutineExit,
		p.Ret,
	)
}

func _GoftraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed goftrace_bpfel_x86.o
var _GoftraceBytes []byte
